export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  COMPLIANCE: '/compliance',
  HOW_TO_USE: '/how-to-use',
  RESOURCES: '/resources',
  SHOWCASE: '/showcase',
  GLOBAL_IMPACT: '/global-impact',
  COMMUNITY_CIRCLES: '/community/language-circles',
  COMMUNITY_KNOWLEDGE_RETURN: '/community/knowledge-return',
  LOGIN: '/login',
  VERIFY_CERTIFICATE: '/certificates/verify',
  DASHBOARD: {
    ROOT: '/dashboard',
    STUDENT: '/dashboard/student',
    DIAGNOSTIC: '/dashboard/student/diagnostic',
    AI_NAVIGATOR: '/dashboard/student/ai-navigator',
    AI_TUTOR: '/dashboard/student/ai-tutor',
    TEACHER: '/dashboard/teacher',
    ADMIN: '/dashboard/admin',
    CREATOR: '/dashboard/creator',
    TESTER: '/dashboard/tester',
    INSTITUTE: '/dashboard/institute',
    MISSION: '/dashboard/mission',
    ACCOUNTING: '/dashboard/accounting',
  },
} as const;
